### ISSUE TITLE
generate pdf

### ISSUE THREAD

**Issue by daniele-zurico** [survivejs/webpack_react#305]
Hi all,
I'm using mac os and I've installed calibre form brew:

- brew cask install calibre
-  export PATH=$PATH://opt/homebrew-cask/Caskroom/calibre/2.46.0/calibre.app/Contents/MacOS

but when I try to run npm start I receive an error:

```
npm start

> survivejs-webpack@1.9.17 start /Users/daniele/Desktop/webpack_react
> npm run generate-pdf


> survivejs-webpack@1.9.17 generate-pdf /Users/daniele/Desktop/webpack_react
> gitbook pdf . ./book.pdf

info: loading book configuration....OK 
info: load plugin gitbook-plugin-highlight ....OK 
info: load plugin gitbook-plugin-search ....OK 
info: load plugin gitbook-plugin-sharing ....OK 
info: load plugin gitbook-plugin-fontsettings ....OK 
info: >> 4 plugins loaded 

No README file

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/Users/daniele/Desktop/webpack_react/node_modules/.bin/npm" "run" "generate-pdf"
npm ERR! node v5.1.0
npm ERR! npm  v2.14.1
npm ERR! code ELIFECYCLE
npm ERR! survivejs-webpack@1.9.17 generate-pdf: `gitbook pdf . ./book.pdf`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the survivejs-webpack@1.9.17 generate-pdf script 'gitbook pdf . ./book.pdf'.
npm ERR! This is most likely a problem with the survivejs-webpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gitbook pdf . ./book.pdf
npm ERR! You can get their info via:
npm ERR!     npm owner ls survivejs-webpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/daniele/Desktop/webpack_react/npm-debug.log

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! survivejs-webpack@1.9.17 start: `npm run generate-pdf`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the survivejs-webpack@1.9.17 start script 'npm run generate-pdf'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the survivejs-webpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run generate-pdf
npm ERR! You can get their info via:
npm ERR!     npm owner ls survivejs-webpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/daniele/Desktop/webpack_react/npm-debug.log
```

this is the npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.3.12
3 info using node@v5.1.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle survivejs-webpack@1.9.17~prestart: survivejs-webpack@1.9.17
6 silly lifecycle survivejs-webpack@1.9.17~prestart: no script for prestart, continuing
7 info lifecycle survivejs-webpack@1.9.17~start: survivejs-webpack@1.9.17
8 verbose lifecycle survivejs-webpack@1.9.17~start: unsafe-perm in lifecycle true
9 verbose lifecycle survivejs-webpack@1.9.17~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/daniele/Desktop/webpack_react/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin://opt/homebrew-cask/Caskroom/calibre/2.46.0/calibre.app/Contents/MacOS/calibre
10 verbose lifecycle survivejs-webpack@1.9.17~start: CWD: /Users/daniele/Desktop/webpack_react
11 silly lifecycle survivejs-webpack@1.9.17~start: Args: [ '-c', 'npm run generate-pdf' ]
12 silly lifecycle survivejs-webpack@1.9.17~start: Returned: code: 1  signal: null
13 info lifecycle survivejs-webpack@1.9.17~start: Failed to exec start script
14 verbose stack Error: survivejs-webpack@1.9.17 start: `npm run generate-pdf`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid survivejs-webpack@1.9.17
16 verbose cwd /Users/daniele/Desktop/webpack_react
17 error Darwin 15.2.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.1.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error survivejs-webpack@1.9.17 start: `npm run generate-pdf`
22 error Exit status 1
23 error Failed at the survivejs-webpack@1.9.17 start script 'npm run generate-pdf'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the survivejs-webpack package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run generate-pdf
23 error You can get their info via:
23 error     npm owner ls survivejs-webpack
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
Something wrong???

**Comment by bebraw** [comment]
Hi,

I haven't looked into the gitbook build in a while. It might make sense to bump gitbook version and tweak the project to build again. Do you want to do a PR against `dev`?

**Comment by daniele-zurico** [comment]
Hi @bebraw I'm not sure what I should do ... first time that I use calibre

**Comment by bebraw** [comment]
@daniele-zurico Can you check out the `dev` branch, nuke *node_modules*, do *npm i*, and hit *npm start* again? The build worked for me after updating the dep.

Note that the built pdf isn't particularly pretty and it's missing a large amount of formatting. That might make it a little painful to read.

**Comment by daniele-zurico** [comment]
I try it now

**Comment by daniele-zurico** [comment]
No same issue:
git branch
* dev
```
git pull
Updating d66666a..7133459
Fast-forward
 README.md    | 2 +-
 package.json | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)
```

rm -rf node_modules/

npm install

npm start

```
npm start

> survivejs-webpack@1.9.17 start /Users/daniele/Desktop/webpack_react
> npm run generate-pdf


> survivejs-webpack@1.9.17 generate-pdf /Users/daniele/Desktop/webpack_react
> gitbook pdf . ./book.pdf

info: loading book configuration....OK 
info: load plugin gitbook-plugin-highlight ....OK 
info: load plugin gitbook-plugin-search ....OK 
info: load plugin gitbook-plugin-sharing ....OK 
info: load plugin gitbook-plugin-fontsettings ....OK 
info: >> 4 plugins loaded 

No README file

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/Users/daniele/Desktop/webpack_react/node_modules/.bin/npm" "run" "generate-pdf"
npm ERR! node v5.1.0
npm ERR! npm  v2.14.8
npm ERR! code ELIFECYCLE
npm ERR! survivejs-webpack@1.9.17 generate-pdf: `gitbook pdf . ./book.pdf`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the survivejs-webpack@1.9.17 generate-pdf script 'gitbook pdf . ./book.pdf'.
npm ERR! This is most likely a problem with the survivejs-webpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gitbook pdf . ./book.pdf
npm ERR! You can get their info via:
npm ERR!     npm owner ls survivejs-webpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/daniele/Desktop/webpack_react/npm-debug.log

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! survivejs-webpack@1.9.17 start: `npm run generate-pdf`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the survivejs-webpack@1.9.17 start script 'npm run generate-pdf'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the survivejs-webpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run generate-pdf
npm ERR! You can get their info via:
npm ERR!     npm owner ls survivejs-webpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/daniele/Desktop/webpack_react/npm-debug.log
```
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.3.12
3 info using node@v5.1.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle survivejs-webpack@1.9.17~prestart: survivejs-webpack@1.9.17
6 silly lifecycle survivejs-webpack@1.9.17~prestart: no script for prestart, continuing
7 info lifecycle survivejs-webpack@1.9.17~start: survivejs-webpack@1.9.17
8 verbose lifecycle survivejs-webpack@1.9.17~start: unsafe-perm in lifecycle true
9 verbose lifecycle survivejs-webpack@1.9.17~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/daniele/Desktop/webpack_react/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin://opt/homebrew-cask/Caskroom/calibre/2.46.0/calibre.app/Contents/MacOS/calibre
10 verbose lifecycle survivejs-webpack@1.9.17~start: CWD: /Users/daniele/Desktop/webpack_react
11 silly lifecycle survivejs-webpack@1.9.17~start: Args: [ '-c', 'npm run generate-pdf' ]
12 silly lifecycle survivejs-webpack@1.9.17~start: Returned: code: 1  signal: null
13 info lifecycle survivejs-webpack@1.9.17~start: Failed to exec start script
14 verbose stack Error: survivejs-webpack@1.9.17 start: `npm run generate-pdf`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid survivejs-webpack@1.9.17
16 verbose cwd /Users/daniele/Desktop/webpack_react
17 error Darwin 15.2.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.1.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error survivejs-webpack@1.9.17 start: `npm run generate-pdf`
22 error Exit status 1
23 error Failed at the survivejs-webpack@1.9.17 start script 'npm run generate-pdf'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the survivejs-webpack package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run generate-pdf
23 error You can get their info via:
23 error     npm owner ls survivejs-webpack
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by bebraw** [comment]
Here's the output I get:

```bash
> survivejs-webpack@1.9.17 start .../survivejs/webpack_react
> npm run generate-pdf


> survivejs-webpack@1.9.17 generate-pdf .../survivejs/webpack_react
> gitbook pdf . ./book.pdf

info: loading book configuration....OK
info: >> 0 plugins loaded
info: start generation with pdf generator
info: clean pdf generatorOK
info: write SUMMARY.html
info: start conversion to pdf ....OK
info: generation is finished
info: >> 1 file(s) generated

Done, without error
```

Any idea why it's loading those plugins for you?

Given the output is subpar, maybe it would make sense to drop Gitbook support altogether...

**Comment by daniele-zurico** [comment]
What you think if we try to introduce something like that?
https://github.com/alanshaw/markdown-pdf

**Comment by bebraw** [comment]
@daniele-zurico I feel the neatest way would be to actually generate the pdf against the current site using something like [html-pdf](https://www.npmjs.com/package/html-pdf). It would take some tweaking (print pdf) but on the plus side we would get excellent formatting as it has been solved on the site already.

I cannot get this short term as I have still left to do with the content. This is my business after all. :+1:

But we can leave this issue open for now so I won't forget. I feel going through the site route would be a worthwhile idea even for the commercial edition as then I would have complete control over the result and I could do certain things that aren't possible in the current way of generating the output.

**Comment by ghilios** [comment]
Ahhh finally figured this out. Update the readme path in book.json to

"structure": {
        "readme": "SUMMARY.md"
    }
