### ISSUE TITLE
page 19, can't webpack

### ISSUE THREAD

**Issue by tomByrer** [survivejs/webpack_react#391]
First example fails to build in node 5.11.0 & 6.0.0:
```bash
~/w/l/s/kanban_app  node_modules/.bin/webpack
/Users/tombyrer/webdev/learn/survivejs/kanban_app/webpack.config.js:11
  output: {
        ^

SyntaxError: Unexpected token :
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/tombyrer/webdev/learn/survivejs/kanban_app/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/Users/tombyrer/webdev/learn/survivejs/kanban_app/node_modules/webpack/bin/webpack.js:39:40)
    at Module._compile (module.js:413:34)
 ✘  ~/w/l/s/kanban_app  node --version
v5.11.0
```
In same environment, your Chapter 2 repo works as expected.

**Comment by bebraw** [comment]
The chapter will be removed in the next version. I've split it up in the second book so the issue should be fixed there. I'll close this then.

Thanks for bringing this up.

**Comment by bebraw** [comment]
Fixed at `dev` so closing.
